---
name: Build and deploy webapp-sample in GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_LOCATION: europe-west8
  GKE_CLUSTER: terraform-gke
  GKE_ZONE: europe-west8-c
  DEPLOYMENT_NAME: backend
  IMAGE: webapp-sample-backend
  REPO: hello-repo

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

#    - name: Docker Login to GAR
#      uses: docker/login-action@v2
#      with:
#        registry: 'europe-west8-docker.pkg.dev'
#        username: _json_key
#        password: ${{ secrets.GCP_CREDENTIALS }}

#    - name: Setup GKE credentials
#      uses: google-github-actions/get-gke-credentials@v0
#      with:
#        cluster_name: ${{ env.GKE_CLUSTER }}
#        location: ${{ env.GKE_ZONE }}

#    - name: 'Cache node_modules'
#      uses: actions/setup-node@v3
#      with:
#        node-version: '16'
#        cache: 'npm'
#        path: /tmp/.buildx-cache

    - name: get npm cache dir
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache docker layers
      id: npm-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Build production image
      uses: docker/build-push-action@v2
      with:
        context: .
#        file: docker/core/Dockerfile
        push: false
        tags: test
        cache-from: type=local,src=${{ steps.npm-cache-dir.outputs.dir }}
        cache-to: type=local,mode=max,dest=${{ steps.npm-cache-dir.outputs.dir }}

        # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache


#    - name: Build
#      run: |-
#        docker build \
#          -t "$GKE_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$GITHUB_SHA" \
#          --build-arg GITHUB_SHA="$GITHUB_SHA" \
#          --build-arg GITHUB_REF="$GITHUB_REF" \
#          .

#    - name: Publish
#      run: |-
#        docker push "$GKE_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$GITHUB_SHA"
